In [1]:
import numpy as np
from scipy import stats

In [2]:
# import dataset
from sklearn import datasets

In [4]:
iris = datasets.load_iris(return_X_y=True)


In [5]:
iris

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [6]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'

In [7]:
# Split the dataset by class values, returns a dictionary
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[-1]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	return separated
 
# Test separating data by class
dataset = [[3.393533211,2.331273381,0],
	[3.110073483,1.781539638,0],
	[1.343808831,3.368360954,0],
	[3.582294042,4.67917911,0],
	[2.280362439,2.866990263,0],
	[7.423436942,4.696522875,1],
	[5.745051997,3.533989803,1],
	[9.172168622,2.511101045,1],
	[7.792783481,3.424088941,1],
	[7.939820817,0.791637231,1]]
separated = separate_by_class(dataset)
for label in separated:
	print(label)
	for row in separated[label]:
		print(row)

0
[3.393533211, 2.331273381, 0]
[3.110073483, 1.781539638, 0]
[1.343808831, 3.368360954, 0]
[3.582294042, 4.67917911, 0]
[2.280362439, 2.866990263, 0]
1
[7.423436942, 4.696522875, 1]
[5.745051997, 3.533989803, 1]
[9.172168622, 2.511101045, 1]
[7.792783481, 3.424088941, 1]
[7.939820817, 0.791637231, 1]


In [9]:
separated

{0: [[3.393533211, 2.331273381, 0],
  [3.110073483, 1.781539638, 0],
  [1.343808831, 3.368360954, 0],
  [3.582294042, 4.67917911, 0],
  [2.280362439, 2.866990263, 0]],
 1: [[7.423436942, 4.696522875, 1],
  [5.745051997, 3.533989803, 1],
  [9.172168622, 2.511101045, 1],
  [7.792783481, 3.424088941, 1],
  [7.939820817, 0.791637231, 1]]}

In [62]:
np.insert(iris[0], 0, iris[1], axis=1)

array([[0. , 5.1, 3.5, 1.4, 0.2],
       [0. , 4.9, 3. , 1.4, 0.2],
       [0. , 4.7, 3.2, 1.3, 0.2],
       [0. , 4.6, 3.1, 1.5, 0.2],
       [0. , 5. , 3.6, 1.4, 0.2],
       [0. , 5.4, 3.9, 1.7, 0.4],
       [0. , 4.6, 3.4, 1.4, 0.3],
       [0. , 5. , 3.4, 1.5, 0.2],
       [0. , 4.4, 2.9, 1.4, 0.2],
       [0. , 4.9, 3.1, 1.5, 0.1],
       [0. , 5.4, 3.7, 1.5, 0.2],
       [0. , 4.8, 3.4, 1.6, 0.2],
       [0. , 4.8, 3. , 1.4, 0.1],
       [0. , 4.3, 3. , 1.1, 0.1],
       [0. , 5.8, 4. , 1.2, 0.2],
       [0. , 5.7, 4.4, 1.5, 0.4],
       [0. , 5.4, 3.9, 1.3, 0.4],
       [0. , 5.1, 3.5, 1.4, 0.3],
       [0. , 5.7, 3.8, 1.7, 0.3],
       [0. , 5.1, 3.8, 1.5, 0.3],
       [0. , 5.4, 3.4, 1.7, 0.2],
       [0. , 5.1, 3.7, 1.5, 0.4],
       [0. , 4.6, 3.6, 1. , 0.2],
       [0. , 5.1, 3.3, 1.7, 0.5],
       [0. , 4.8, 3.4, 1.9, 0.2],
       [0. , 5. , 3. , 1.6, 0.2],
       [0. , 5. , 3.4, 1.6, 0.4],
       [0. , 5.2, 3.5, 1.5, 0.2],
       [0. , 5.2, 3.4, 1.4, 0.2],
       [0. , 4

In [69]:
# Split the dataset by class values, returns a dictionary
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[0]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	return separated

In [70]:
temp_dataset = np.insert(iris[0], 0, iris[1], axis=1)

In [71]:
separate_by_class(temp_dataset)

{0.0: [array([0. , 5.1, 3.5, 1.4, 0.2]),
  array([0. , 4.9, 3. , 1.4, 0.2]),
  array([0. , 4.7, 3.2, 1.3, 0.2]),
  array([0. , 4.6, 3.1, 1.5, 0.2]),
  array([0. , 5. , 3.6, 1.4, 0.2]),
  array([0. , 5.4, 3.9, 1.7, 0.4]),
  array([0. , 4.6, 3.4, 1.4, 0.3]),
  array([0. , 5. , 3.4, 1.5, 0.2]),
  array([0. , 4.4, 2.9, 1.4, 0.2]),
  array([0. , 4.9, 3.1, 1.5, 0.1]),
  array([0. , 5.4, 3.7, 1.5, 0.2]),
  array([0. , 4.8, 3.4, 1.6, 0.2]),
  array([0. , 4.8, 3. , 1.4, 0.1]),
  array([0. , 4.3, 3. , 1.1, 0.1]),
  array([0. , 5.8, 4. , 1.2, 0.2]),
  array([0. , 5.7, 4.4, 1.5, 0.4]),
  array([0. , 5.4, 3.9, 1.3, 0.4]),
  array([0. , 5.1, 3.5, 1.4, 0.3]),
  array([0. , 5.7, 3.8, 1.7, 0.3]),
  array([0. , 5.1, 3.8, 1.5, 0.3]),
  array([0. , 5.4, 3.4, 1.7, 0.2]),
  array([0. , 5.1, 3.7, 1.5, 0.4]),
  array([0. , 4.6, 3.6, 1. , 0.2]),
  array([0. , 5.1, 3.3, 1.7, 0.5]),
  array([0. , 4.8, 3.4, 1.9, 0.2]),
  array([0. , 5. , 3. , 1.6, 0.2]),
  array([0. , 5. , 3.4, 1.6, 0.4]),
  array([0. , 5.2, 3.5,

In [76]:
cls, counts = np.unique(iris[1], return_counts=True)
cls, counts

(array([0, 1, 2]), array([50, 50, 50]))

array([0, 1, 2])